### PR TITLE
Fix PVS-Studio warnings.

### LINKED ISSUE #20: PVS-Studio flagged: use `make_unique` in the `FilterModelConfig` classes
PVS Studio flags this in both FilterModelConfig `buildIntegerator()` functions:

**Reasoning**: https://pvs-studio.com/en/docs/warnings/v824/

### PR DESCRIPTION
**Pull request by nevack**
Fixes #20 #21 #23 #26

### CODE REVIEW

File: src/builders/residfp-builder/residfp/WaveformCalculator.cpp [hunk 1]
```diff
@@ -194,7 +194,9 @@ matrix_t* WaveformCalculator::buildTable(ChipModel model)
         wftable[6][idx] = calculateCombinedWaveform(cfgArray[2], 6, idx);
         wftable[7][idx] = calculateCombinedWaveform(cfgArray[3], 7, idx);
     }
-
+#ifdef HAVE_CXX11
+    return &(CACHE.emplace_hint(lb, cw_cache_t::value_type(cfgArray, wftable))->second);
+#endif
```
Comment (drfiemost) [inline src/builders/residfp-builder/residfp/WaveformCalculator.cpp:199]: Would be better to have an #else/#endif to avoid dead code

File: src/builders/residfp-builder/residfp/EnvelopeGenerator.h [hunk 2]
```diff
@@ -169,7 +169,8 @@ class EnvelopeGenerator
         decay(0),
         sustain(0),
         release(0),
-        env3(0)
+        env3(0),
+        dac()
```
Comment (drfiemost) [inline src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: dac is initialized when setChipModel is called from the SID constructor so there's no chance of uninitialized accesses, like it's done in WaveformGenerator (not sure why it's not flagged there).
Maybe it would be better to mark the variable with //-V730_NOINIT

**Review by drfiemost — CHANGES_REQUESTED** [review]

File: src/builders/residfp-builder/residfp/EnvelopeGenerator.h (hunk 2 above)
Comment (nevack) [reply src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: This is just default initialization of array, it should not change behavior, just suppress any warnings or style linters.
Correct me, if i'm wrong.

Comment (kcgen) [reply src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: PVS is a static inspector, and gives recommendations on code quality regardless of how the overall program hangs together.

In this case, a user can construct an `Envelope e` object, then call `e.output()` and get handed and uninitialzed `dac[0xaa]` float.

Comment (drfiemost) [reply src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: > This is just default initialization of array, it should not change behavior, just suppress any warnings or style linters.
> Correct me, if i'm wrong.

You're right, it would initialize the array with zeros, but it will be then overwritten when setChipModel is called so it's just wasting time.


> However taken on its own, a user can construct an `Envelope` object and immediately call its `output()` member function, and get handed and uninitialized `dac[0xaa]` float.

Sure but this is not the case here. Anyway as mentioned in issue #34 I plan to rework this part so it doesn't really matter.

Comment (kcgen) [reply src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: > I plan to rework this part so it doesn't really matter.
:+1:

File: src/builders/residfp-builder/residfp/WaveformCalculator.cpp (hunk 1 above)
Comment (drfiemost) [reply src/builders/residfp-builder/residfp/WaveformCalculator.cpp:199]: To be more precise, if HAVE_CXX11 is defined there would be two return statements, so the second one should be included in an #else/#endif block.

File: src/builders/residfp-builder/residfp/EnvelopeGenerator.h (hunk 2 above)
Comment (drfiemost) [reply src/builders/residfp-builder/residfp/EnvelopeGenerator.h:173]: Please revert this one as it will be solved in another way as explained above.

**Comment by drfiemost** [comment]
@nevack waiting for the requested changes to merge this PR, thanks

**Comment by nevack** [comment]
> @nevack waiting for the requested changes to merge this PR, thanks

Done
